services:
    postgres:
      image: postgres:15.0
      restart: always
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - ./init_db.sql:/docker-entrypoint-initdb.d/init-db.sql
      ports:
        - "5432:5432"