services:
    uuidy_app:
      build:
        context: ../
        dockerfile: docker/Dockerfile

      restart: always
      depends_on:
        uuidy_postgres:
          condition: service_healthy

      environment:
        - TG_BOT_TOKEN=<TG_BOT_TOKEN>
        - PG_RO_URL=postgresql://ro_user:ro_user@uuidy_postgres:5432/postgres
        - PG_RW_URL=postgresql://postgres:postgres@uuidy_postgres:5432/postgres
        - JWT_SECRET=kashdkqwhiu12h3uih6573asiudh12h3uiashdiu3455412h3iasnadu12hbdasd12y
        - ADMIN_PASSWORD=noBodyKnowsThatIReadTheirNotes))))))0000
        - SERVICE_HOST=<SERVICE_HOST>

      ports:
        - "7777:5000"
      networks:
        - uuidy-network

    uuidy_postgres:
      image: postgres:15.0
      restart: always
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
        interval: 30s
        timeout: 10s
        retries: 5

      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

      networks:
        - uuidy-network

      volumes:
        - ./init_db.sql:/docker-entrypoint-initdb.d/init-db.sql

networks:
  uuidy-network:
    driver: bridge